parallel:
    environment: bsub
    pre_run:
        - 'export PATH=${HOME}/Anaconda/bin:$PATH'
        - 'source activate paper_calliope_time'

solver: gurobi
solver_io: lp

debug:
    keep_temp_files: false
    symbolic_solver_labels: false
    echo_solver_log: true
