name: uk-calliope

channels:
    - anaconda
    - conda-forge

dependencies:
    - python=3.5
    - numpy=1.10.1
    - matplotlib=1.5.0
    - pandas=0.17.1
    - pytables=3.2.3.1
    - numexpr=2.4.6
    - pyyaml=3.11
    - pip:
        - Pyomo==4.2.10784
        - calliope==0.3.7
        - click==3.3
